apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grupo-teste
  # Geralmente aplicações de controle do Argo ficam no namespace 'argocd'
  namespace: argocd
spec:
  project: default # Ou o projeto específico definido pelo admin
  source:
    # URL do repositório Git onde estão os manifestos (Deployment, Service, etc)
    repoURL: 'https://github.com/PhrL0/argocd-senai-cluster.git'
    targetRevision: HEAD
    # Pasta que o ArgoCD vai observar exclusivamente para este grupo
    path: apps/grupo-teste
  destination:
    server: 'https://kubernetes.default.svc'
    # Namespace isolado que criamos anteriormente
    namespace: grupo-teste
  syncPolicy:
    automated:
      prune: true      # Remove recursos no cluster que não existem mais no Git
      selfHeal: true   # Corrige automaticamente mudanças manuais (kubectl edit)
    syncOptions:
      - CreateNamespace=false # O namespace já é criado pelo admin via outro YAML